# Generated by Django 6.1.1 on 2026-10-01 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_aijob_llmusagelog_medicationmention'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmusagelog',
            name='prompt_version',
            field=models.CharField(default='v1', max_length=16),
        ),
    ]
